### ISSUE TITLE
Action server endpoint for different deployment options

### ISSUE THREAD

**Issue by SebaDro** [cdhiraj40/envirocar-rasa-bot#2]
# Description
Per default, the action server endpoint url points to "http://rasa-actions-server:5055/webhook":
https://github.com/cdhiraj40/envirocar-rasa-bot/blob/3613833e5c558804069967f107fc54109020f512/endpoints.yml#L15
This is the endpoint for a Docker-based deployment. However, if you want to run the Rasa server and Rasa Actions server without Docker, you have to set the URL to "localhost:5055/webhook", manually.

# How to solve
I'd suggest to set the endpoint URL to "localhost:5055/webhook" within the `endpoints.yml` and add an environment variable for this parameter with the URL for Docker deployment to the `docker-compose.yml`. If the parameter can not be set this way, add an extra `endpoints.yml` which addresses the Docker deployment and will be injected via volume.

**Comment by cdhiraj40** [comment]
@SebaDro solved via commit: https://github.com/cdhiraj40/envirocar-rasa-bot/commit/e2dd293322361657c941958e450308b6960adfdc
